<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <!-- 参考 https://blog.fundebug.com/2017/10/09/unhandled-pomise-rejection/ -->
    <script>
        new Promise(resolve => {
            foo.bc
            resolve(123)
        }).then(data => {
            return 123
        }).then(data => {
            console.log(data)
        }, err => {
            foo.bc
            console.log(err, '----')
        }).catch(err => {
            // foo.bc
            // console.log(err)
        }).finally(() => {
            console.log(112)
        })
        // 捕获未处理的promise错误
        window.addEventListener('unhandledrejection', event => {
            console.log(event.reason, '捕获未处理的promise错误'); // 打印"Hello, Fundebug!"
        });
        // 当一个Promise错误最初未被处理，但是稍后又得到了处理，则会触发rejectionhandled事件：
        window.addEventListener("rejectionhandled", event => {
            console.log("Promise rejected; reason: " + event.reason);
        }, false);
    </script>
</body>

</html>